# Build customization
builds:
  - binary: heketi
    goos:
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: tar.gz

dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    # GOARM of the built binary that should be used.
    goarm: ''
    # Name of the built binary that should be used.
    binary: heketi
    # Docker image name.
    image: g0194776/heketi
    # Path to the Dockerfile (from the project root).
    dockerfile: extras/docker/fromsource/Dockerfile
    # Path to the Dockerfile (from the project root).
    tag_templates:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - heketi.json
      - heketi-start.sh