dist: xenial
language: go
go: '1.11.x'


env:
  # needed for the snap pipe:
  - PATH=/snap/bin:$PATH


before_install:
  - docker build -t antmoveh/heketi -f extras/docker/fromsource/Dockerfile


# needed for the docker pipe
services:
  - docker

after_success:
  # docker login is required if you want to push docker images.
  # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push antmoveh/heketi .